### ISSUE TITLE
gradlew Build modifies test data which is under version control 

### ISSUE THREAD

**Issue by kabl** [scenarioo/scenarioo#606] opened 2017-03-29 14:44 UTC
After a ```./gradlew clean build test war``` run following files are modified: 

```
kabl$ git status
On branch feature/591-diff-viewer-improvements
Your branch is up-to-date with 'origin/feature/591-diff-viewer-improvements'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   scenarioo-docu-generation-example/src/test/resources/example/documentation/scenarioDocuExample/wikipedia-docu-example-dev/2014-04-19/build.xml
        modified:   scenarioo-docu-generation-example/src/test/resources/example/documentation/scenarioDocuExample/wikipedia-docu-example-dev/2014-05-19/build.xml
        modified:   scenarioo-docu-generation-example/src/test/resources/example/documentation/scenarioDocuExample/wikipedia-docu-example/2014-02-21/build.xml
        modified:   scenarioo-docu-generation-example/src/test/resources/example/documentation/scenarioDocuExample/wikipedia-docu-example/2014-03-19/build.xml

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        scenarioo-server/src/test/resources/org/scenarioo/business/diffViewer/diffScreenshot.png

no changes added to commit (use "git add" and/or "git commit -a")
```

These files are under version control. They should not change because of a Build.

**Comment by bruderol** [comment] 2017-03-29 14:54
@kabl I think it is not a bug - but kind of a feature - can explain it to you - but you are right, it is not ideal.

**Comment by bruderol** [comment] 2017-09-19 11:43
@kabl thought about it again - you are right, the tests should never manipulate the data directly. We have to change the tests to copy it into some build folder before reading and manipulating it. this causes problems all the time, therefore I will change it and I removed the nice to have tag.

**Comment by bruderol** [comment] 2017-10-04 09:18
Problem is in ScenariooValidatorTest - it does manipulate the checked in sources directly instead of in a temporary folder - will refactor that using a TemporaryFolder - see also https://garygregory.wordpress.com/2010/01/20/junit-tip-use-rules-to-manage-temporary-files-and-folders/

**Comment by bruderol** [comment] 2017-10-04 10:09
fixed in https://github.com/scenarioo/scenarioo/pull/622

**Closed by bruderol** 2017-10-04 10:09 UTC
Labels: 2 - Working, bug
