### ISSUE TITLE
Improve wait for server startup after deployment (e.g. wait for log statement)

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#704] opened 2018-05-28 06:47 UTC
Currently we just wait for a certain time (2 minutes?) which is not a very stable and makes builds unnecessarily long time blocking. 

Since It works pretty well at the moment though, so there's no high urgency to fix this.

**Comment by adiherzog** [comment] 2018-05-28 06:47
Related to #703

**Comment by bruderol** [comment] 2018-05-28 11:35
yes, would be useful to improve that. Thanks for opening!

**Comment by bruderol** [comment] 2018-12-22 03:03
Assigned to myself. Want to get rid of this tech debt, also because it might help to get faster build feedback if during startup of scenarioo already something fails

**Comment by eggerschwiler** [comment] 2019-05-20 08:25
Duplicate of #637 ?

**Comment by eggerschwiler** [comment] 2019-07-08 07:28
Has been resolved with issue #637

**Closed by eggerschwiler** 2019-07-08 07:28 UTC
Labels: 3 - Done, Prio-2-Important, type:TechDebt
