### ISSUE TITLE
Build-Failure: http://54.88.202.24/jenkins/job/deploy-demo-and-run-e2e-tests/701/

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#472] opened 2016-03-31 21:43 UTC
See http://54.88.202.24/jenkins/job/deploy-demo-and-run-e2e-tests/701/

Alle Tests failen mit:

Failed: unexpected alert open: {Alert text : You will lose unsaved changes if you reload this page}

Offensichtlich ein Problem, dass da irgendwas mit dem Unsaved Changes Popup vom Issue Sketcher nicht zuverlässig weggeräumt wurde und dann zu instabilen Tests führt.

Also the build before (different problems, maybe also with UI Sketcher because first failed test is UI sketcher test) should be analysed:
http://54.88.202.24/jenkins/job/deploy-demo-and-run-e2e-tests/700

If we let such things happen, without analysing it and allways trying to find the root cause, the e2e tests will get more unstable

**Comment by adiherzog** [comment] 2016-04-08 05:55
It looks like there is only one issue with the build that can be reproduced (https://github.com/scenarioo/scenarioo/issues/473). Therefore I close this one.

**Closed by adiherzog** 2016-04-08 05:55 UTC
