### ISSUE TITLE
Bug: Tabs in Issue Sketcher read-only view missing

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#489] opened 2016-04-13 19:11 UTC
If one views a sketch in read-only mode there should be tabs to switch between the sketch, the original screenshot and the metadata. They went away with the Angular 1.5 upgrade.

Furthermore the "Sketch successfully saved" message after saving a sketch is not styled like a green success message anymore. The same is probably to for the failure message.

This is not urgent but has to be fixed before the next release after 2.2.

**Comment by danielsuter** [comment] 2016-04-15 08:42
@adiherzog 
I will look into this. Can you please give detailled information, how I can reproduce this expected behaviour? I also think it would make sense to test such functionality with e2e Tests.

**Comment by bruderol** [comment] 2016-04-16 11:09
Scenario 1:
* If a Sketch is allready available, just choose one from the Tab "Sketches"
* You should see the page which should present the tabs

Scenario 2:
* Browse to a step
* Click on "Create Sketch"
* Enter properties for the Issue / Sketch
* Save it
* Close it
* You should see the page where this tabs would be expected.

**Comment by danielsuter** [comment] 2016-05-10 08:08
@bruderol @adiherzog 
If you mean the tabs "sketch" and "original screenshot", it's fixed. The feature still seems to be buggy though. After playing and jumping around I get exceptions in the console:

![image](https://cloud.githubusercontent.com/assets/6558042/15139578/2ca3bfd0-1697-11e6-95f9-defb611ebda7.png)

**Comment by bruderol** [comment] 2016-11-15 22:46
tested in chorem, works fine for me.
@adiherzog @danielsuter can we close?

**Comment by danielsuter** [comment] 2016-11-16 07:09
I fixed the problem mentioned in the issue. Could you see the error message I described above?

**Comment by bruderol** [comment] 2016-11-16 09:39
didnt see it, I close it

**Closed by bruderol** 2016-11-16 09:39 UTC
Labels: 2 - Working, bug, Prio-1
