### ISSUE TITLE
Java 8 migration / cleanup

### ISSUE THREAD

**Issue by patrickschweizer** [scenarioo/scenarioo#598] opened 2017-03-07 15:03 UTC
It seams that their is an issue with incompatible guava versions (fulltext search feature)
+--- com.google.guava:guava-base:r03
|    \--- com.google.guava:guava-annotations:r03
+--- org.elasticsearch:elasticsearch:2.3.1
|    +--- com.google.guava:guava:18.0
(List is probably incomplete, please comment if you find another one, thanks!)

Upgrade all 3rd party libs to Java 8 compatible ones:
- RESTEasy
- Javaassist
- guava
- Elasticsearch

This also fixes #616 then.

**Acceptance criteria**
* [ ] Runs as before --> test
* [ ] Runs in docker ---> test?
* [ ] Runs at least with our tomcat versions used --> update elasticsearch (and if needed tomcat) on CI ?
* [ ] In case new tomcat version is needed mention it in documentation and in changelog
* [ ] It is possible to use lambdas/closures in our REST controllers --> test and cleanup in code
* [ ] ElasticSearch works as before --> test!
* [ ] Changelog mentions breaking change to Elasticsearch version (and if needed other breaking changes)
* [ ] Generic logging of all REST request works as before.

**Comment by bruderol** [comment] 2017-03-27 14:51
we have to clarify if there is no branch yet, where @danielsuter started to do things like that.

@adiherzog @danielsuter probably @kabl has some time to work on this.

At least we should use our own scenarioo-java dependency from new maven central repo release if not yet?

**Comment by adiherzog** [comment] 2017-11-29 09:00
@bruderol Please clarify what the issue is.

**Comment by bruderol** [comment] 2017-11-29 12:40
@til77 and @patrickschweizer in our last meeting @til77 mentioned that there were some troubles with some libraries ... we wanted to address that before our next release but can not reproduce the problem. Can youhelp us with reproducing the exact problem?

**Comment by til77** [comment] 2017-12-08 12:54
Just found a mail that mentions the issue:

>  •	Die neue "Full Text Search" Funktion hat bei uns zu Problemen mit den guava Abhängigkeiten geführt. Kann es sein, dass dieses Feature unter Linux nicht funktioniert auf Grund der Reihenfolge der geladenen Libraries. 
> +--- com.google.guava:guava-base:r03
> |    \--- com.google.guava:guava-annotations:r03
> +--- org.elasticsearch:elasticsearch:2.3.1
>      | ...
> |    +--- com.google.guava:guava:18.0
> Mit Version 5 von ElasticSearch wurde die Abhängigkeit zu guava scheinbar entfernt dafür ist natürlich Java 8 Voraussetzung. Auch hier erscheint uns ein Update der Library gerechtfertigt.
>

**Comment by bruderol** [comment] 2018-05-13 09:17
@cgrossde @eggerschwiler I cleaned up the story to have those acceptancde criteria that we have to do / verify before we can merge that for the release.

All remaining open points on the PR are not mandatory for closing this story and gettting it merged so far, so please move those to another follow up issue that could then be finalised after the release:
see PR #685

**Comment by bruderol** [comment] 2018-05-13 22:43
currently not working at all with new RestEasy version - some services not work anymore, some changed slightly the json result format (because RESTeasy somehow changed how they consider XML annotations for JSON serialization, it seems, which we have).

I partially fixed the change to the backend json format, on my branch for thiss issue here - but I forgot to to adjust the javascript tests of the client, that is what fails right now.

**Comment by bruderol** [comment] 2018-05-15 07:32
See #699 

Ich habe dort einiges gefixt/verbessert, jetzt gibt es noch folgende Probleme zu beheben:

1. RestEasy Path Konflikte: neue Version interpretiert @Path teilweise anders ---> man sollte jetzt im Server Log entsprechende Fehlermeldungen sehen (dank den hinzugefügten ExceptionHandlern).

2. Teilweise werden Collections in RestEasy 3 anders serialisiert, wenn sie nur mit @XmlElement annotiert wurden --> z.B. "labels" (ev. ausschliesslich?) kommen anders im Frontend an, gewisse Tests failen deshalb, ich habe das partiell gefixt. Hier ist zu überlegen ob wir die `scenarioo-java` fixen wollen (Achtung: Xml-Format darf nicht gebrochen werden!) oder den angefangenen Weg (im Frontend anpassen) weiterführen wollen.

3. Fehlender Elasticsearch 5 Cluster mit Name "elasticsearch" auf CI --> Full Text Search e2e tests failen.

**Closed** 2018-05-30 11:16 UTC
Labels: 2 - Working, Prio-1, topic:techDebt
