### ISSUE TITLE
Bug: Page variant browsing link is broken

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#432] opened 2015-10-06 12:52 UTC
feature #247 seems not to work anymore, as expected (on develop branch).

**Comment by adiherzog** [comment] 2015-10-29 21:49
@bruderol I think this still works, just tested it. Could you please check again?

**Comment by bruderol** [comment] 2015-10-30 07:43
For me it does not work (clicking the page-variants link has no effect)

Tested In Firefox on following page:
http://54.88.202.24/scenarioo-develop/#/step/Find%20Page/find_multiple_results/searchResults.jsp/0/0?branch=wikipedia-docu-example&build=last%20successful

**Comment by bruderol** [comment] 2015-10-30 07:46
In Chrome it works.
In IE same as Firefox (not work).

It is not just the link that does not work:
also the mouse-over-tooltip-popups on the navigation buttons are not working in Firefox and IE.

**Comment by xeronimus** [comment] 2015-11-02 15:59
yep. the problem is that you nested a anchor tag (<a href="url to page variant">Page Variant 2 of 24</a>)  inside a button tag.

**Comment by adiherzog** [comment] 2015-11-03 07:44
Thanks @xeronimus. I just tested it and merged it into the release-2.1 branch.

**Closed by adiherzog** 2015-11-03 07:44 UTC
Labels: bug

**Comment by bruderol** [comment] 2015-11-04 17:13
perfect. Thank you so much!

**Comment by bruderol** [comment] 2015-11-04 18:38
but the same problem still exists with all other navigation buttons: popup tooltips not working anymore.
@adiherzog you changed this once to buttons and since then all the tooltips not work anymore.

I will open a new issue.
