### ISSUE TITLE
Screenshots for successful testcases

### ISSUE THREAD

**Issue by rupjit09** [scenarioo/scenarioo#1042] opened 2021-03-06 12:02 UTC
I am getting screenshots for only failed testcases, but my requirement is to get snapshot for all the testcases for visual regression test of all the pages

In protractor.conf.js i have appended the below code

`var scenariooConfig = {

        // Directory inside which to store the report files
        targetDirectory: './scenarioReports',

        // Identification of the current branch or software version being tested and the id of the run of the build jub,
        // usually fetched from your environment (e.g. passed via `process.env` or asking git tooling)
        // using this identifiers you can later link to reports of that same build in the Viewer Web App.
        branchName: process.env.GIT_BRANCH || 'unknown_branch',  // use your real branch (or product version) that you are documenting here
        buildName: process.env.BUILD_ID || 'build_' + new Date(), // better use unique build identifier, if available

        // Optional: additional documentation information about tested product version and branch:
        revision: process.env.BUILD_TAG || '0.0.0', // use e.g. git version here (e.g. `git describe --always`)
        branchDescription: process.env.JENKINS_URL || '',

        // Define a unique human readable identifier of the page the test is currently on (usually a part of the URL)
        pageNameExtractor: function (url) {
          return url.pathname;
        },

        // Enable automatic screenshot step generated on each expectation failed
        reportStepOnExpectationFailed: true,
        

        // Enable to write last step of a scenario automatically for both failed and passed (=successful) test scenarios
        recordLastStepForStatus: {
           failed: true,
           success: true
        }

      };
      scenarioo.setupJasmineReporter(jasmine, scenariooConfig );
  }`

How do i configure to get snapshot for both success and failed testcases

**Comment by bruderol** [comment] 2021-03-09 13:09
Hi @rupjit09
did you already check our example here:

https://github.com/scenarioo/scenarioo-js/tree/develop/example

Is there something you do differently than in our example?

how do you write your tests - can you show us an example of your tests and the rest of the protractor configuration?

and which version of protractor, jasmine etc. are you using? It might be a version problem.

**Comment by bruderol** [comment] 2021-03-17 16:23
Hi @rupjit09 

Do you have some more information for us on  that? Or is this not relevant to you anymore? could you solve it?

We will be happy to help you, but if we do not get more information, I will close the issue soon as resolved.

**Comment by bruderol** [comment] 2021-03-30 12:58
I close this since we received no further information about the problem. 

@rupjit09 feel free to reopen once you find time to give us more information such we can reproduce it.

**Closed as completed by bruderol** 2021-03-30 12:58 UTC
