### ISSUE TITLE
Remove bower

### ISSUE THREAD

**Issue by danielsuter** [scenarioo/scenarioo#457] opened 2016-03-05 13:21 UTC
Probably all our dependencies could be managed by NPM. We started removing it for our jass challenge and it worked well. We should check, if this is also a possibility for the scenarioo-client.

https://gofore.com/stop-using-bower/
https://medium.com/@nickheiner/why-my-team-uses-npm-instead-of-bower-eecfe1b9afcb

**Comment by bruderol** [comment] 2016-03-09 18:12
yes, that would be really great! I also do not like this bower thing.

**Comment by adiherzog** [comment] 2016-03-26 22:48
Duplicate of #409

**Closed by adiherzog** 2016-03-26 22:48 UTC
Labels: topic:infrastructure, topic:webapp
