### ISSUE TITLE
Diff Viewer: Styling and UI issues

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#717] opened 2018-06-01 15:43 UTC
Various layout issues and other ui problems on the step comparison view (diff viewer) and other screens with diff info indicators that are disturbing and lead to wrong interpretation - in prioritized order:

1. [important] when toggeling details to be displayed or hidden while on the comparison view the diff highlights are not properly aligned to the underlying screen (reload of page fixes it): 
![image](https://user-images.githubusercontent.com/3780183/40849819-3ba64ba6-65c3-11e8-8818-1f37545566de.png)
   * [x] should be automatically alligned correctly without need to reload

3. [important] Change indicator tooltip hidden when details are not shown:
![image](https://user-images.githubusercontent.com/3780183/41702178-74b4908a-752f-11e8-979e-110c3a5b7cda.png)
   * [x] user should see the tooltip on the change indicator on the screen (open to left)
 
4. [nice to have] Comparison view is difficult to understand for added screens - most buttons could be removed for added screens:
![image](https://user-images.githubusercontent.com/3780183/41702143-4ece56ee-752f-11e8-8f4d-a137361429fd.png)
   * [x] Hide button for "Other Screen"
   --> see [comment](#issuecomment-492097689)
   * [x] Hide button to toggle between current and other screen
   * [x] Highlight the label "Added Step: No Comparison" by displaying it in green color (same as "added"-icon in tab)

5. [nice to have] Change indicator is currently empty for added screens on added scenario page:
![image](https://user-images.githubusercontent.com/3780183/41702159-60b0fe20-752f-11e8-996f-63c132d4c55d.png)
   * [x] Display "added" for all steps in an added scenario (or leave the indicator away?? )

6. [nice to have] Use Case Table and Details overlap (probably because of the text length in the Description field). Same issue could be present in the scenarios list.
![image](https://user-images.githubusercontent.com/3780183/41702216-9579fc6a-752f-11e8-963d-2c95811cd81e.png)
    * [x] Use Case and Scenario Table and Details on the right should never overlap, also not with diff info and long description texts in details

7. [nice to have] On the Page Details page, if any of Use Case, Scenario, Step or Page have a label, then all those headings appear, even for those that do not have labels.
![177-labels-on-step-page](https://user-images.githubusercontent.com/7665276/57626344-f905e200-7595-11e9-871b-b04d1247948e.png)
   * [x] Only the parts that have labels are listed.

8. [nice-to-have] Further issues without screenshots:
    * [x] After submitting a comparison using "Create Comparison", the Comparisons list should be displayed and refreshed to show that the comparison is being calculated (was not implemented on branch of this story, @bruderol will do it on other branch for #872)
    * [x] color of removed and added rows (use cases, scenarios) in tables is not very well distinguishable from normal row colors and especially not from current row selection when using up and down keys in tables - probably not at all distinguishable for color blind people. 
    * ~Add "Space" key to keyboard shortcuts documentation -> Toggles screenshots in step comparison view~ removed since not works without focus   --> comment by @eggerschwiler: "Space" only worked when I navigate with "Tab" to the button or when the button was pressed by a mouse click first. 

9. [nice-to-have] The "+" Tooltip is not completely visible on Scenario page.
![717-show-hide-tooltip-not-shown](https://user-images.githubusercontent.com/7665276/57686630-37ed7380-763a-11e9-9e1b-e90732f1d8ea.png)
    * [x] Open tooltip to the right

Moved to other issues:

2. [important] Details move over the comparison screen on small screens ("responsive"):
![image](https://user-images.githubusercontent.com/3780183/40849849-5384d77e-65c3-11e8-8e97-c61a8dc144d9.png)
   * [ ] details should move below the whole screen comparison area on small screen
   --> See [comment](#issuecomment-491750596)
   --> Moved to issue #826 because there is no quick and easy fix at the moment.

**Comment by adiherzog** [comment] 2018-06-01 15:44
@bruderol Found these two layout issues by accident. We should fix them before the release.

**Comment by bruderol** [comment] 2018-06-01 16:02
yeah, minor things, but yes, we should fix it

**Comment by adiherzog** [comment] 2018-06-21 06:51
@bruderol I added some more layout / UI issues that I found when testing.

**Comment by bruderol** [comment] 2018-06-22 09:06
I would appreciate if we could split up such thing - now there are many issues on one. Hard to prioritize

**Comment by mi-we** [comment] 2019-04-03 16:10
@bruderol proposes to do the following: split into two stories (minimum) one for sketcher are and one for diff viewer issues. The diff viewer (e.g. showing steps as added for added scenario) is a much higher prio as the other sketcher stuff.

**Comment by bruderol** [comment] 2019-04-03 17:46
@adiherzog: could you please next time not use screenshots of a step of the self docu for bug reports - it does not help to understand bugs, when you see in the screenshots scenario itself - this makes my brain explode ;-)  - it confused me and I first thought this issue is about the sketcher partially.

**Comment by bruderol** [comment] 2019-04-03 18:41
Ok, I know think that it is ok for now to have all this diff viewer issues on one story, but since we might only tackle some of them (see priorization that I added now),  we have to split it, once we solved the important ones. I first missunderstood many of the described issues, becuase the sketcher in the screenshots confused me and it lokked to me like too much different topics in one issue.

@mi-we @adiherzog I prioritized all the issues and precised them to be better undertsandable what needs to be done. See acceptance criterias with checkboxes in description

**Comment by eggerschwiler** [comment] 2019-05-13 09:36
Regarding issue 2: "Details move over the comparison screen on small screens ("responsive")"
The problem is that if "Highlight Changes" is activated, then the screenshot-image has the following style: "position absolute". This does not work very well with responsive design.
The issue is even worse if the comparison type "Side-by-Side" is selected on a small screen. Then both screenshots are rendered in the same place and thus only the image normally on the right is visible.

Could someone look into this with more css styling experience?

**Comment by eggerschwiler** [comment] 2019-05-14 06:33
Regarding issue 4: "Comparison view is difficult to understand for added screens - most buttons could be removed for added screens"
I removed the button "Other Screen", but this might lead to confusion as well. E.g. if a user has selected the "Other Screen" view, is stepping through a Scenario and comes to an added screen page, then the "Other Screen" option is still selected and only the info "Added step: no comparison screen available" is visible. This might be confusing as well. So maybe it would be better to only hide the Toggle button and keep the "Other Screen" deactivated?
![717-other-screen-with-added-screen](https://user-images.githubusercontent.com/7665276/57675650-d5d54400-7622-11e9-963c-f9900f305d97.png)
@adiherzog: What do you think?

**Comment by eggerschwiler** [comment] 2019-05-14 11:06
I completed all issues, that I know how to fix. 

Issue 2 should be adressed by someone with in depth css and absolute/relative positioning know-how.

**Comment by mi-we** [comment] 2019-06-19 12:56
> Regarding issue 4: "Comparison view is difficult to understand for added screens - most buttons could be removed for added screens"
> I removed the button "Other Screen", but this might lead to confusion as well. E.g. if a user has selected the "Other Screen" view, is stepping through a Scenario and comes to an added screen page, then the "Other Screen" option is still selected and only the info "Added step: no comparison screen available" is visible. This might be confusing as well. So maybe it would be better to only hide the Toggle button and keep the "Other Screen" deactivated?
> ![717-other-screen-with-added-screen](https://user-images.githubusercontent.com/7665276/57675650-d5d54400-7622-11e9-963c-f9900f305d97.png)
> @adiherzog: What do you think?

IMHO, the best way would be to just always display the current screen on added steps and hide all the buttons. This way the selection of the "other screen" button is preserved when the user jumps to the  next step. This might need a bit more logic in the code but in I think regarding the user experience it is better.

**Comment by bruderol** [comment] 2019-06-21 10:09
@adiherzog we resolved almost everything in this issue (or opened other issues for what was not doable). Can you have a look at the colors regarding "not distinguishable for color blind people" and open a separate issue for improving this, if you think it still needs to be improved further. 

i think we can then close this issue here as soon as PR is merged.

**Comment by eggerschwiler** [comment] 2019-06-21 11:29
PR was merged. Closing this issue.

**Closed by eggerschwiler** 2019-06-21 11:29 UTC
Labels: 3 - Done, Prio-2-Important, type:Bug

**Comment by adiherzog** [comment] 2019-06-21 14:26
@eggerschwiler Thanks a lot for all the fixes!

**Comment by adiherzog** [comment] 2019-06-21 15:10
@eggerschwiler @bruderol I tested almost all fixes in Google Chrome and they look fine. I could not test the color of added / removed rows because there are no such rows in our demo. But I don't think that's a big issue anyway because the label makes it clear which ones are added / removed.

**Comment by bruderol** [comment] 2019-06-22 18:25
@adiherzog of course there are such rows in our demo --- see here in this build of our demo data: http://demo.scenarioo.org/scenarioo-release-5.0/?#/?comparison=To%20Projectstart&branch=wikipedia-docu-example-dev&build=last%20successful&tab=usecases
